"""
row3_late_fusion.py
===================
Row 3 of the EEG+EMG fusion taxonomy: **decision-level (late) fusion**.

Two *independent* models — one per modality — are trained in isolation, each
produces calibrated class probabilities, and a shallow meta-learner combines the
PROBABILITY VECTORS (never the embeddings). This file is deliberately built so
that the only thing crossing the modality boundary is a vector of probabilities;
the moment you feed embeddings to the combiner you have silently built Row 2
(intermediate fusion) and thrown away the two properties that justify Row 3:
independence (one modality cannot starve the other during training) and
auditability (you get an honest standalone accuracy for each branch for free).

Why this design, branch by branch
----------------------------------
EEG branch — ShallowConvNet (Schirrmeister 2017, "shallow" variant).
    The square -> mean-pool -> log pipeline literally computes log band-power,
    i.e. a second-order (variance) statistic. That is the right inductive bias
    for speech-imagery EEG, where the discriminative content is oscillatory
    power rather than an evoked waveform. (If a contamination/evoked ablation
    later says the signal is phase-locked, swap in an xDAWN front-end here.)

EMG branch — hybrid 1D temporal CNN  ++  Hudgins time-domain features.
    EMG carries discriminative content well above the EEG band (fast bursts,
    sharp onset transients), so it gets its OWN front-end at its OWN sampling
    rate — not an EEG-tuned net. The learned 1D conv captures waveform shape the
    hand features miss; the Hudgins features (MAV/WL/ZC/SSC + RMS) inject a
    strong, data-efficient prior. NOTE: with genuinely good data the marginal
    value of the Hudgins side-vector collapses (the CNN can learn those
    features); keep it as a cheap robustness/interpretability anchor and expect
    ablating it to cost ~nothing. Toggle with `emg_use_hudgins`.

Combiner — temperature-calibrated, out-of-fold probability stacking.
    Two disciplines that are easy to get wrong and that this file enforces:
      (1) Temperature-scale each branch BEFORE stacking. Otherwise the meta
          learner just learns to trust whichever branch is more overconfident,
          not whichever is more correct.
      (2) Train the meta-learner on OUT-OF-FOLD branch predictions, generated by
          an internal (group-aware) CV, never on in-sample predictions — else it
          overfits training-set confidence and the held-out gain evaporates.

RA / alignment toggle (EEG only, default OFF)
---------------------------------------------
We were previously over-confident in Riemannian Alignment. Two facts demote it
here: (a) in a deep pipeline there is no tangent-space step, so "RA" degrades to
per-session Euclidean whitening (the geometric-vs-arithmetic-mean distinction
that makes RA *RA* stops mattering); (b) good multi-session re-donned data + a
deep net learns session-invariance from the data itself, which substitutes for
what alignment patched. So alignment lives here as a cheap, label-free *ablation*
on the EEG branch — `align_eeg="none" | "ea"` — default "none". It is NOT applied
to EMG, whose dominant nonstationarity (electrode reseating changing which muscle
each contact sees) is a label-conditional/rotational shift that mean-recentering
cannot fix. Let the ablation number decide whether it earns its place.

Interface (mirrors models.TorchClassifier, extended to two modalities)
----------------------------------------------------------------------
    clf = LateFusionStacker(n_classes=K)
    clf.fit(Xe, Xm, y, groups=subject_or_session_ids)   # Xe:(n,Ce,T) Xm:(n,Cm,T)
    clf.predict(Xe, Xm) / clf.predict_proba(Xe, Xm)
    clf.branch_scores_     # {'eeg':oof_acc, 'emg':oof_acc} — the audit numbers
"""

from __future__ import annotations

import numpy as np
import torch
import torch.nn as nn
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.model_selection import StratifiedKFold, GroupKFold
from sklearn.model_selection import StratifiedShuffleSplit, GroupShuffleSplit, ShuffleSplit
from sklearn.neural_network import MLPClassifier

try:
    from tqdm.auto import tqdm
except ImportError:                      # graceful no-op if tqdm absent
    def tqdm(it=None, **k):
        return it if it is not None else iter([])

# =============================================================================
#  CONSTANTS
# =============================================================================
SEED = 42
EEG_F_TEMPORAL = 40          # ShallowConvNet temporal filters
EEG_KERNEL_TIME = 25         # temporal kernel (~half a 50 Hz cycle at 1 kHz->decim)
EEG_POOL = 75                # mean-pool width (Schirrmeister uses 75)
EEG_POOL_STRIDE = 15
EMG_CONV_CHANNELS = (32, 64) # 1D CNN width per stage on the EMG branch
EMG_KERNELS = (11, 7)
EMG_STRIDES = (4, 2)
HUDGINS_ZC_THRESH = 1e-5     # deadzone so baseline noise doesn't inflate ZC/SSC
STACK_HIDDEN = (32,)         # the "shallow MLP" meta-learner
DEFAULT_OOF_FOLDS = 5
EPS = 1e-6


def _device(dev=None):
    return dev or ("cuda" if torch.cuda.is_available() else "cpu")


# =============================================================================
#  Hudgins time-domain features  (also useful standalone in your data pipeline)
# =============================================================================
def hudgins_td(x: torch.Tensor, zc_thresh: float = HUDGINS_ZC_THRESH) -> torch.Tensor:
    """Classic 4 Hudgins features + RMS, per channel.

    x : (B, C, T)  ->  (B, C*5)  in the order [MAV, WL, ZC, SSC, RMS] per channel.

    ZC and SSC use a deadzone threshold so that low-amplitude baseline noise does
    not manufacture spurious crossings (the standard fix vs naive sign-change
    counts). These are *features*, not a layer to learn through — sign() has zero
    a.e. gradient, which is fine; they act as a fixed, deterministic transform.
    """
    mav = x.abs().mean(dim=2)                                   # (B,C)
    wl = x.diff(dim=2).abs().mean(dim=2)                        # waveform length
    # zero crossings: sign flips between adjacent samples, gated by amplitude
    s = x[..., 1:] * x[..., :-1]
    big = (x[..., 1:] - x[..., :-1]).abs() > zc_thresh
    zc = ((s < 0) & big).float().mean(dim=2)
    # slope sign changes: sign flips of the first difference
    d = x.diff(dim=2)
    ssc = ((d[..., 1:] * d[..., :-1] < 0) &
           (d[..., 1:].abs() > zc_thresh)).float().mean(dim=2)
    rms = x.pow(2).mean(dim=2).clamp_min(EPS).sqrt()
    return torch.cat([mav, wl, zc, ssc, rms], dim=1)            # (B, C*5)


# =============================================================================
#  EEG branch — ShallowConvNet (logits)
# =============================================================================
class ShallowConvNet(nn.Module):
    """Schirrmeister shallow net: temporal conv -> spatial conv -> square ->
    mean-pool -> log -> dropout -> linear. The square/log is the band-power
    prior. Flatten size is computed by a dummy forward (no hard-coded T//k bug)."""

    def __init__(self, n_channels, n_times, n_classes,
                 f_temporal=EEG_F_TEMPORAL, k_time=EEG_KERNEL_TIME,
                 pool=EEG_POOL, pool_stride=EEG_POOL_STRIDE, dropout=0.5):
        super().__init__()
        self.temporal = nn.Conv2d(1, f_temporal, (1, k_time), padding=(0, k_time // 2),
                                  bias=False)
        self.spatial = nn.Conv2d(f_temporal, f_temporal, (n_channels, 1), bias=False)
        self.bn = nn.BatchNorm2d(f_temporal)
        self.pool = nn.AvgPool2d((1, pool), stride=(1, pool_stride))
        self.drop = nn.Dropout(dropout)
        with torch.no_grad():
            flat = self._features(torch.zeros(1, 1, n_channels, n_times)).flatten(1).shape[1]
        self.fc = nn.Linear(flat, n_classes)

    def _features(self, x):                       # x: (B,1,C,T)
        x = self.bn(self.spatial(self.temporal(x)))
        x = x.pow(2)                              # square  -> variance
        x = self.pool(x)                          # mean-pool over time
        x = x.clamp_min(EPS).log()                # log band-power
        return self.drop(x)

    def forward(self, x):
        if x.dim() == 3:
            x = x.unsqueeze(1)                     # (B,1,C,T)
        return self.fc(self._features(x).flatten(1))


# =============================================================================
#  EMG branch — hybrid 1D temporal CNN  ++  Hudgins features (logits)
# =============================================================================
class EMGHybridNet(nn.Module):
    """1D temporal CNN over raw EMG, optionally concatenated with the Hudgins
    time-domain feature vector before the classifier head."""

    def __init__(self, n_channels, n_times, n_classes,
                 conv_channels=EMG_CONV_CHANNELS, kernels=EMG_KERNELS,
                 strides=EMG_STRIDES, dropout=0.5, use_hudgins=True):
        super().__init__()
        self.use_hudgins = use_hudgins
        layers, c_in = [], n_channels
        for c_out, k, s in zip(conv_channels, kernels, strides):
            layers += [nn.Conv1d(c_in, c_out, k, stride=s, padding=k // 2, bias=False),
                       nn.BatchNorm1d(c_out), nn.ELU(), nn.Dropout(dropout)]
            c_in = c_out
        self.conv = nn.Sequential(*layers)
        with torch.no_grad():
            conv_flat = self.conv(torch.zeros(1, n_channels, n_times)).mean(dim=2).shape[1]
        feat_dim = conv_flat + (n_channels * 5 if use_hudgins else 0)
        self.fc = nn.Linear(feat_dim, n_classes)

    def forward(self, x):                          # x: (B,C,T)
        z = self.conv(x).mean(dim=2)               # global average pool over time
        if self.use_hudgins:
            z = torch.cat([z, hudgins_td(x)], dim=1)
        return self.fc(z)


# =============================================================================
#  Euclidean alignment (the demoted "RA" toggle, EEG only, default off)
# =============================================================================
class EuclideanAlignment:
    """Label-free per-set whitening: reference R = mean trial covariance, then
    x -> R^{-1/2} x. In a deep pipeline this is what 'RA' collapses to (no
    tangent-space step), hence the name. Fit on train; in deployment you would
    re-estimate R unsupervised on each new session's own trials."""

    def fit(self, X):                              # X: (n,C,T)
        covs = np.einsum("nct,ndt->ncd", X, X) / X.shape[2]
        R = covs.mean(axis=0)
        w, V = np.linalg.eigh(R)
        self.W_ = V @ np.diag(1.0 / np.sqrt(np.maximum(w, EPS))) @ V.T
        return self

    def transform(self, X):
        return np.einsum("cd,ndt->nct", self.W_, X).astype(np.float32)


# =============================================================================
#  Minimal trainer (mirrors models.TorchClassifier: group-aware inner val,
#  early stopping, class weighting, AdamW) — kept compact and self-contained.
# =============================================================================
def _fit_net(net, X, y, n_classes, groups=None, *, lr=1e-3, weight_decay=1e-3,
             batch_size=32, max_epochs=200, patience=20, val_frac=0.2, seed=SEED,
             dev=None, verbose=False, desc="net"):
    dev = _device(dev)
    torch.manual_seed(seed); np.random.seed(seed)
    X = np.asarray(X, np.float32); y = np.asarray(y)
    if groups is not None and len(np.unique(groups)) >= 2:
        tr, va = next(GroupShuffleSplit(1, test_size=val_frac, random_state=seed)
                      .split(X, y, groups))
    else:
        try:
            tr, va = next(StratifiedShuffleSplit(1, test_size=val_frac, random_state=seed)
                          .split(X, y))
        except ValueError:                       # a class too rare to stratify
            tr, va = next(ShuffleSplit(1, test_size=val_frac, random_state=seed)
                          .split(X))
    net = net.to(dev)
    counts = np.bincount(y, minlength=n_classes).astype(np.float64)
    cw = torch.tensor(counts.sum() / (len(counts) * np.maximum(counts, 1)),
                      dtype=torch.float32, device=dev)
    crit = nn.CrossEntropyLoss(weight=cw)
    opt = torch.optim.AdamW([p for p in net.parameters() if p.requires_grad],
                            lr=lr, weight_decay=weight_decay)
    Xt, yt = torch.tensor(X), torch.tensor(y, dtype=torch.long)
    dl = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(Xt[tr], yt[tr]), batch_size=batch_size, shuffle=True)
    Xva, yva = Xt[va].to(dev), yt[va].to(dev)
    best, best_state, bad = np.inf, None, 0
    pbar = tqdm(range(max_epochs), desc=desc, disable=not verbose, leave=False)
    for _ in pbar:
        net.train()
        for xb, yb in dl:
            opt.zero_grad(); crit(net(xb.to(dev)), yb.to(dev)).backward(); opt.step()
        net.eval()
        with torch.no_grad():
            vloss = crit(net(Xva), yva).item()
        if vloss < best - 1e-4:
            best, bad = vloss, 0
            best_state = {k: v.detach().cpu().clone() for k, v in net.state_dict().items()}
        else:
            bad += 1
            if bad >= patience:
                break
        if verbose:
            pbar.set_postfix(val=f"{best:.3f}", patience=f"{bad}/{patience}")
    if best_state is not None:
        net.load_state_dict(best_state)
    return net, dev


def _fit_temperature(logits, y, dev):
    """Single-parameter temperature scaling on a held-out slice (Guo 2017)."""
    logits = torch.tensor(np.asarray(logits, np.float32), device=dev)
    yt = torch.tensor(np.asarray(y), dtype=torch.long, device=dev)
    logT = torch.zeros(1, device=dev, requires_grad=True)
    opt = torch.optim.LBFGS([logT], lr=0.1, max_iter=50)
    crit = nn.CrossEntropyLoss()

    def closure():
        opt.zero_grad()
        loss = crit(logits / logT.exp(), yt)
        loss.backward()
        return loss
    opt.step(closure)
    return float(logT.exp().item())


def _softmax_np(z, T=1.0):
    z = np.asarray(z, np.float64) / T
    z = z - z.max(1, keepdims=True)
    e = np.exp(z)
    return e / e.sum(1, keepdims=True)


# =============================================================================
#  The late-fusion stacker
# =============================================================================
class LateFusionStacker(BaseEstimator, ClassifierMixin):
    """Decision-level fusion of an EEG ShallowConvNet branch and an EMG hybrid
    branch via temperature-calibrated, out-of-fold probability stacking."""

    def __init__(self, n_classes, *, n_times_eeg=None, n_times_emg=None,
                 align_eeg="none", emg_use_hudgins=True, oof_folds=DEFAULT_OOF_FOLDS,
                 lr=1e-3, weight_decay=1e-3, batch_size=32, max_epochs=200,
                 patience=40, seed=SEED, device=None, verbose=True,
                 eeg_pretrained=None, emg_pretrained=None, freeze_encoders=False):
        self.n_classes = n_classes
        self._k = n_classes
        self.n_times_eeg = n_times_eeg
        self.n_times_emg = n_times_emg
        self.align_eeg = align_eeg            # "none" | "ea"  (default off)
        self.emg_use_hudgins = emg_use_hudgins
        self.oof_folds = oof_folds
        self.lr = lr; self.weight_decay = weight_decay
        self.batch_size = batch_size; self.max_epochs = max_epochs
        self.patience = patience; self.seed = seed; self.device = device
        self.verbose = verbose
        self.eeg_pretrained = eeg_pretrained
        self.emg_pretrained = emg_pretrained
        self.freeze_encoders = freeze_encoders

    # ---- branch builders -------------------------------------------------
    def _new_eeg(self, Ce, T):
        net = ShallowConvNet(Ce, T, self._k)
        if self.eeg_pretrained:
            from pretrain import transfer_load, freeze_module
            transfer_load(net, self.eeg_pretrained, verbose=self.verbose, tag="R3 EEG")
            if self.freeze_encoders:        # freeze everything except the head
                for n, p in net.named_parameters():
                    if not n.startswith("fc"):
                        p.requires_grad = False
        return net

    def _new_emg(self, Cm, T):
        net = EMGHybridNet(Cm, T, self._k, use_hudgins=self.emg_use_hudgins)
        if self.emg_pretrained:
            from pretrain import transfer_load
            transfer_load(net, self.emg_pretrained, verbose=self.verbose, tag="R3 EMG")
            if self.freeze_encoders:        # freeze the conv feature extractor only
                for n, p in net.named_parameters():
                    if n.startswith("conv"):
                        p.requires_grad = False
        return net

    def _maybe_align(self, Xe, fit_on=None):
        if self.align_eeg == "none":
            return Xe
        if fit_on is not None:                # fit reference on train rows only
            self._ea_ = EuclideanAlignment().fit(fit_on)
        return self._ea_.transform(Xe)

    # ---- training kwargs shared by both branches -------------------------
    def _tk(self):
        return dict(lr=self.lr, weight_decay=self.weight_decay,
                    batch_size=self.batch_size, max_epochs=self.max_epochs,
                    patience=self.patience, seed=self.seed, dev=self.device,
                    verbose=self.verbose)

    def fit(self, Xe, Xm, y, groups=None, classes=None):
        Xe = np.asarray(Xe, np.float32); Xm = np.asarray(Xm, np.float32)
        y = np.asarray(y)
        self.classes_ = np.unique(y) if classes is None else np.asarray(classes)
        self._k = len(self.classes_)
        y_idx = np.searchsorted(self.classes_, y)
        n = len(y)
        self.n_times_eeg = self.n_times_eeg or Xe.shape[2]
        self.n_times_emg = self.n_times_emg or Xm.shape[2]

        # ---- 1) out-of-fold branch probabilities (group-aware) ----------
        # The stacker MUST see predictions on data the branch did not train on.
        # Cap the fold count to the number of groups available (else GroupKFold
        # raises when n_splits > n_groups) and fall back to stratified CV when
        # there are too few groups to split on.
        if groups is not None and len(np.unique(groups)) >= 2:
            k = min(self.oof_folds, len(np.unique(groups)))
            split_iter = GroupKFold(n_splits=k).split(Xe, y_idx, groups)
        else:
            k = min(self.oof_folds, int(np.min(np.bincount(y_idx))))
            split_iter = StratifiedKFold(max(2, k), shuffle=True,
                                         random_state=self.seed).split(Xe, y_idx)

        oof = np.zeros((n, 2 * self._k), np.float64)
        for tr, te in split_iter:
            g_tr = None if groups is None else np.asarray(groups)[tr]
            # EEG branch on this fold
            Xe_tr = self._maybe_align(Xe[tr], fit_on=Xe[tr])
            net_e, dev = _fit_net(self._new_eeg(Xe.shape[1], self.n_times_eeg),
                                  Xe_tr, y_idx[tr], self._k, g_tr,
                                  desc="R3 EEG (oof)", **self._tk())
            # EMG branch on this fold
            net_m, _ = _fit_net(self._new_emg(Xm.shape[1], self.n_times_emg),
                                Xm[tr], y_idx[tr], self._k, g_tr,
                                desc="R3 EMG (oof)", **self._tk())
            # calibrate each branch's temperature on the *fold-test* logits,
            # then store calibrated probabilities as the OOF stacking features
            with torch.no_grad():
                Xe_te = self._maybe_align(Xe[te])     # uses ref fit on this fold's train
                ze = net_e(torch.tensor(Xe_te, device=dev)).cpu().numpy()
                zm = net_m(torch.tensor(Xm[te], device=dev)).cpu().numpy()
            Te = _fit_temperature(ze, y_idx[te], dev)
            Tm = _fit_temperature(zm, y_idx[te], dev)
            oof[te, :self._k] = _softmax_np(ze, Te)
            oof[te, self._k:] = _softmax_np(zm, Tm)

        # branch audit numbers (the whole point of Row 3)
        self.branch_scores_ = {
            "eeg": float((oof[:, :self._k].argmax(1) == y_idx).mean()),
            "emg": float((oof[:, self._k:].argmax(1) == y_idx).mean()),
        }

        # ---- 2) train the shallow-MLP meta-learner on OOF probabilities --
        self.stacker_ = MLPClassifier(hidden_layer_sizes=STACK_HIDDEN, max_iter=500,
                                      random_state=self.seed, early_stopping=True)
        self.stacker_.fit(oof, y_idx)

        # ---- 3) refit each branch on ALL data + final temperature -------
        # (use a held-out slice purely for the final temperature estimate)
        if groups is not None and len(np.unique(groups)) >= 2:
            cal_tr, cal_te = next(GroupShuffleSplit(1, test_size=0.2,
                                  random_state=self.seed).split(Xe, y_idx, groups))
        else:
            cal_tr, cal_te = next(StratifiedShuffleSplit(1, test_size=0.2,
                                  random_state=self.seed).split(Xe, y_idx))
        g_all = None if groups is None else np.asarray(groups)[cal_tr]
        Xe_all = self._maybe_align(Xe[cal_tr], fit_on=Xe[cal_tr])
        self.eeg_, dev = _fit_net(self._new_eeg(Xe.shape[1], self.n_times_eeg),
                                  Xe_all, y_idx[cal_tr], self._k, g_all,
                                  desc="R3 EEG (final)", **self._tk())
        self.emg_, _ = _fit_net(self._new_emg(Xm.shape[1], self.n_times_emg),
                                Xm[cal_tr], y_idx[cal_tr], self._k, g_all,
                                desc="R3 EMG (final)", **self._tk())
        self._dev = dev
        with torch.no_grad():
            ze = self.eeg_(torch.tensor(self._maybe_align(Xe[cal_te]), device=dev)).cpu().numpy()
            zm = self.emg_(torch.tensor(Xm[cal_te], device=dev)).cpu().numpy()
        self.T_eeg_ = _fit_temperature(ze, y_idx[cal_te], dev)
        self.T_emg_ = _fit_temperature(zm, y_idx[cal_te], dev)
        return self

    def _branch_probs(self, Xe, Xm):
        Xe = self._maybe_align(np.asarray(Xe, np.float32))
        Xm = np.asarray(Xm, np.float32)
        with torch.no_grad():
            ze = self.eeg_(torch.tensor(Xe, device=self._dev)).cpu().numpy()
            zm = self.emg_(torch.tensor(Xm, device=self._dev)).cpu().numpy()
        return np.hstack([_softmax_np(ze, self.T_eeg_), _softmax_np(zm, self.T_emg_)])

    def predict_proba(self, Xe, Xm):
        return self.stacker_.predict_proba(self._branch_probs(Xe, Xm))

    def predict(self, Xe, Xm):
        col = self.predict_proba(Xe, Xm).argmax(1)
        return self.classes_[self.stacker_.classes_[col]]

    def branch_predict(self, Xe, Xm):
        """Per-modality hard predictions (calibrated) on new data — lets an outer
        CV loop score EEG-alone and EMG-alone on the SAME held-out fold as the
        fused model, which is the honest way to read the audit."""
        P = self._branch_probs(Xe, Xm)
        K = self._k
        return {"eeg": self.classes_[P[:, :K].argmax(1)],
                "emg": self.classes_[P[:, K:].argmax(1)]}


# =============================================================================
#  Smoke test
# =============================================================================
if __name__ == "__main__":
    rng = np.random.default_rng(0)
    n, Ce, Cm, T, K = 80, 16, 16, 256, 4
    g = np.repeat(np.arange(8), 10)                       # 8 "sessions"
    y = rng.integers(0, K, n)
    # inject a weak class signal into both modalities so fit is non-degenerate
    Xe = rng.standard_normal((n, Ce, T)).astype(np.float32)
    Xm = rng.standard_normal((n, Cm, T)).astype(np.float32)
    for k in range(K):
        Xe[y == k, k % Ce] += 0.6 * np.sin(np.linspace(0, 6, T))
        Xm[y == k, k % Cm] += 0.6
    clf = LateFusionStacker(n_classes=K, oof_folds=3, max_epochs=5, patience=3)
    clf.fit(Xe, Xm, y, groups=g)
    p = clf.predict(Xe, Xm)
    print("branch audit (OOF acc):", clf.branch_scores_)
    print("fused train acc:", round(float((p == y).mean()), 3),
          "| T_eeg=%.2f T_emg=%.2f" % (clf.T_eeg_, clf.T_emg_))
    print("SMOKE OK")
